### ISSUE TITLE
true-zen :TZAtaraxis not working properly

### ISSUE THREAD

**Issue by sseneca** [Pocco81/true-zen.nvim#86]
Enabling makes neovim look like this:

![](https://user-images.githubusercontent.com/25619071/181915147-79071d4d-e248-4f42-bac5-f50beab386b9.png)

Toggling again gives me this error message:

```
Error executing vim.schedule lua callback: ...ack/packer/start/true-zen.nvim/lua/true-zen/ataraxis.lua:129: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_is_valid'
        ...ack/packer/start/true-zen.nvim/lua/true-zen/ataraxis.lua:129: in function 'layout'
        ...ack/packer/start/true-zen.nvim/lua/true-zen/ataraxis.lua:204: in function <...ack/packer/start/true-zen.nvim/lua/true-zen/ataraxis.lua:182>
```

My config:

- [Installing it with Packer](https://git.ssene.ca/sseneca/dotfiles/src/branch/main/.config/nvim/lua/plugins/init.lua#L178)
- [true-zen config](https://git.ssene.ca/sseneca/dotfiles/src/branch/main/.config/nvim/lua/plugins/true-zen.lua)
- [twilight config as well](https://git.ssene.ca/sseneca/dotfiles/src/branch/main/.config/nvim/lua/plugins/twilight.lua)

**Comment by Pocco81** [comment]
should be working now :tada:

**Comment by sseneca** [comment]
Much better, thanks! Is there a way to fix lualine looking like this after toggling it on?

![2022-07-30T15:53:13,509058789+01:00](https://user-images.githubusercontent.com/25619071/181919863-482e0064-c0e4-409d-a781-493321ab629d.png)

**Comment by ned-si** [comment]
Just discovered the plugin and I love it.

Unfortunately, I can still reproduce the error. 

[Here](https://github.com/ned-si/dotfiles/tree/master/nvim) are my dotfiles.
